services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    ports:
      - 8100:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./app:/app
    environment:
      - TZ=Europe/Vienna
      - GLUTSPEICHER_CRYPTO_KEY=00000000000000000000000000000000
    working_dir: /app
    entrypoint: ["./Glutspeicher Server"]
